export const COUCHBASE_CONNECTION_TOKEN = 'COUCHBASE_CONNECTION_TOKEN';
export const COUCHBASE_MODULE_OPTIONS = 'COUCHBASE_MODULE_OPTIONS';
export const COUCHBASE_CONNECTIONS = 'COUCHBASE_CONNECTIONS';
